### ISSUE TITLE
File history lost after migration

### ISSUE THREAD

**Issue by akaranta** [hraban/tomono#56] opened 2024-08-02 07:21 UTC
After combining two repositories to a monorepo, the history for a given file does not seem accessible anymore. 

git log -p -- path/to/myfile.txt

only gives a single commit.

Any way to get around this?

**Comment by hraban** [comment] 2024-08-02 07:45
This works locally--do you have a reproducible example maybe?

**Comment by hraban** [comment] 2024-08-02 07:45
(don't forget --follow)

**Comment by akaranta** [comment] 2024-08-02 07:58
Hi!

Thanks for a very quick answer!

I did also try the --follow option. That resulted in no commits at all being shown. :/

Unfortunately I don't have any publicly available repro sample. Me and my colleagues are experiencing this after the migration, but unfortunately the repository is proprietary and I can not provide access to it. 
If there is something I can do in the repo to help troubleshoot the issue I'll be happy to do that.

**Comment by hraban** [comment] 2024-08-02 09:14
Sorry but I cannot reproduce this locally. Example:

```sh
$ tomono <<EOF
https://github.com/hraban/tomono tomono
https://git.code.sf.net/p/sbcl/sbcl sbcl
EOF

(...snip...)
$ cd core
$ git checkout master
$ git log --follow sbcl/README
(.. lots of commits...)
```

Make sure you are running the latest version of git.

**Comment by akaranta** [comment] 2024-08-02 12:50
It seems there was one crucial detail I neglected to mention. When combining the repositories, let's call them r1 and r2, the resulting repository R has the directory structure

R
|-r1
|-r2

In practice this means that the files have moved. I assume this has the same effect as renaming files, which was reported in another issue:

https://github.com/hraban/tomono/issues/6

At least the symptoms we observe are exactly the same.

Thus this is likely a duplicate issue. And as there was no solution to that issue the same goes for this one. :/

**Comment by hraban** [comment] 2024-08-02 15:34
> It seems there was one crucial detail I neglected to mention. When combining the repositories, let's call them r1 and r2, the resulting repository R has the directory structure

Yes, that's expected, as it is the default mode of operation for `tomono`. That's also what happens in that sample script I posted.

> In practice this means that the files have moved. I assume this has the same effect as renaming files, which was reported in another issue

That issue has since been fixed and git --follow does now give you the full history, pre the move. N.B. the code example I gave, I'll paste it again here below but please try it out yourself to see the effect:

```sh
$ tomono <<EOF
https://github.com/hraban/tomono tomono
https://git.code.sf.net/p/sbcl/sbcl sbcl
EOF

(...snip...)
$ cd core
$ git checkout master
$ git log --follow sbcl/README
(.. lots of commits...)
```

on my machine this gives me a full history. The files are moved to their subdirectory as per usual.

I just want to go over my last message again to make sure we cut out potential distractions:

- Did you check this script locally on your machine?
- Did you ensure you have the last version of git?

**Comment by akaranta** [comment] 2024-08-05 08:10
Hi,

I did test combining tomono and scbl as you did above and there git log works just fine. So apparently the problem is somehow specific to our combined repository.

$ git --version
git version 2.46.0.windows.1

Should be the latest version of git.

**Comment by akaranta** [comment] 2024-08-05 10:30
I just observed something strange. 

The file history is available if one uses the path to the file as it would have been before creating the monorepository. 

So to use the actual command line I am using locally:

```
NAPA+nakk@N6WV7CK3 MINGW64 /c/work/one (bugfix/NAPA-68901-local-exucution-of-std-tests-)                          
$ ls napa.net/NapaCore/src/Core/FEM/Impl/Topology/TopologyFactory.cs                                              
ls: cannot access 'napa.net/NapaCore/src/Core/FEM/Impl/Topology/TopologyFactory.cs': No such file or directory    
                                                                                                                  
NAPA+nakk@N6WV7CK3 MINGW64 /c/work/one (bugfix/NAPA-68901-local-exucution-of-std-tests-)                          
$ ls napa/napa.net/NapaCore/src/Core/FEM/Impl/Topology/TopologyFactory.cs                                         
napa/napa.net/NapaCore/src/Core/FEM/Impl/Topology/TopologyFactory.cs                                              
                                                                                                                  
NAPA+nakk@N6WV7CK3 MINGW64 /c/work/one (bugfix/NAPA-68901-local-exucution-of-std-tests-)                          
$ git log --follow -p -- napa.net/NapaCore/src/Core/FEM/Impl/Topology/TopologyFactory.cs

```

**Comment by hraban** [comment] 2024-08-05 22:37
Ok, thanks for feeding back. Since the issue is on your end and we cannot repro, I'm going to close this issue.

If you can create a reproducible bug report I'm happy to have a look, but for now I'm going to close this issue.

(Context: I maintain this software for free, and while I'm happy to fix bugs in this application itself, I am not keen on giving free labor to for-profit companies who keep their code closed source :). It's starting to look like the issue is on your end, at which point this just becomes an unpaid consulting gig. Sorry, good luck and best wishes!)

**Closed as completed** 2024-08-05 22:37 UTC

**Comment by akaranta** [comment] 2024-08-06 08:51
Hi,

Yes, I totally understand and appreciate all the advice and help you already gave. 

As a developer I know that is next to impossible to troubleshoot an issue you can't reproduce.

I'll post here if I find out anything more about why the file history is available (only) with the original path after creating the monorepo.
