### ISSUE TITLE
case-sensitive branch-names break on Windows

### ISSUE THREAD

**Issue by asinning** [hraban/tomono#45] opened 2022-07-29 12:45 UTC
If two repos have branches which differ only in upper/lower-case, then the merge will fail on Windows

**Comment by hraban** [comment] 2022-07-29 20:09
Interesting, but is that a git ↔ Windows problem, or a tomono specific problem?

Can you do this on Windows?

```
git init
git commit -m root --allow-empty
git checkout -b foo
git checkout -b FOO
```

If not, I think the problem is a wider git + windows one, not a tomono one. You'd have to get this fixed upstream.

See also:

- https://stackoverflow.com/questions/31814663/git-remote-two-branches-same-name-different-case
- https://stackoverflow.com/questions/15371866/why-is-git-capitalizing-my-branch-name-prefix

**Comment by hraban** [comment] 2022-07-29 20:10
the workaround they propose in that SO question seems like a good choice btw: clone one of the repos to a case sensitive filesystem, rename the branch to match the other's case, then merge that in, instead.

**Comment by hraban** [comment] 2022-07-29 20:15
Closing as WONTFIX since this seems to be by design on Windows, and the problems are upstream, not here. There is a work-around (see SO). Feel free to continue discussing if relevant.

**Closed as completed by hraban** 2022-07-29 20:15 UTC
